### ISSUE TITLE
スマホだとボタン操作を受け付けない

### ISSUE THREAD

**Issue by gsc2000** [gsc2000/OkatronAI#23]
PCのクリックとはイベントの取り方が違うのかも？？

OkatronServer | INFO:     172.18.0.1:49234 - "GET /video_feed HTTP/1.1" 200 OK
OkatronServer | INFO:     192.168.10.121:50575 - "GET /video_feed HTTP/1.1" 200 OK
OkatronServer | INFO:     192.168.10.121:50576 - "GET /mode/2/move_top HTTP/1.1" 200 OK
↑ここで止まる

**Comment by burudogbaby** [comment]
IPhoneとAndroidのみ対応済み
IPad要確認
