### ISSUE TITLE
サーボの首振り機能時に手動と同じ制御にする

### ISSUE THREAD

**Issue by gsc2000** [gsc2000/OkatronAI#62]
現在は一気に端っこまで動くようになっているが、手動制御と同じように５度ずつ動くようにする。

**Comment by burudogbaby** [comment]
手動操作と同じようにするのが困難だったので、5度ずつのメッセージを送ることで対応

**Comment by gsc2000** [comment]
ワンクリックで端まで動いてしまう不具合があった。
対応済み→確認待ち
